"""
n8n Webhook Testing Script
Tests all available n8n webhooks and logs their responses
"""

import requests
import json
from datetime import datetime

# Base URL for n8n webhooks
N8N_BASE_URL = "https://vitcornu.app.n8n.cloud/webhook"

def print_header(title):
    print("\n" + "=" * 60)
    print(f"  {title}")
    print("=" * 60)

def test_endpoint(method, endpoint, params=None, data=None, description=""):
    """Test an n8n webhook endpoint and print the response"""
    url = f"{N8N_BASE_URL}/{endpoint}"
    
    print(f"\n🔍 Testing: {description}")
    print(f"   Method: {method}")
    print(f"   URL: {url}")
    
    if params:
        print(f"   Params: {params}")
    if data:
        print(f"   Body: {json.dumps(data, indent=2)}")
    
    try:
        if method == "GET":
            response = requests.get(url, params=params)
        elif method == "POST":
            response = requests.post(url, params=params, json=data)
        elif method == "PUT":
            response = requests.put(url, params=params, json=data)
        else:
            print("   ❌ Unsupported HTTP method")
            return
        
        print(f"\n   ✅ Status Code: {response.status_code}")
        
        # Try to parse JSON response
        try:
            json_response = response.json()
            print(f"   📦 Response:")
            print(json.dumps(json_response, indent=4))
        except:
            print(f"   📦 Response (text):")
            print(response.text[:500])  # Print first 500 chars
            
    except Exception as e:
        print(f"   ❌ Error: {str(e)}")

def main():
    print_header(f"n8n Webhook Test Suite - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # ========== BRAND ENDPOINTS ==========
    print_header("BRAND ENDPOINTS")
    
    # Test 1: Get Active Brands
    test_endpoint(
        "GET", 
        "GetActiveBrands",
        description="Get all active brands"
    )
    
    # Test 2: Get Brand Details
    test_endpoint(
        "GET", 
        "GetBrandDetails",
        params={"brand_name": "VitCornu"},
        description="Get details for VitCornu brand"
    )
    
    # ========== CONTENT BACKLOG ENDPOINTS ==========
    print_header("CONTENT BACKLOG ENDPOINTS")
    
    # Test 3: Fetch Backlog Ideas (Approved for Briefing)
    test_endpoint(
        "GET", 
        "FetchBacklogIdeas",
        description="Get all items with status 'Approved for Briefing'"
    )
    
    # Test 4: Fetch Item Details (if you have an ID)
    # Replace '1' with an actual ID from your Google Sheets
    test_endpoint(
        "GET", 
        "FetchItemDetails",
        params={"id": "1"},
        description="Get details for item ID 1"
    )
    
    # ========== PAVE SCORING ENDPOINT ==========
    print_header("PAVE SCORING (NEW!)")
    
    # Test 4.5: Analyze Keyword with PAVE Scoring
    test_endpoint(
        "POST",
        "AnalyzeKeyword_Backend",
        params={
            "Brand_Name": "VitCornu",
            "Keyword": "Best Running Shoe"
        },
        description="Analyze keyword with AI PAVE scoring + Bing search"
    )
    
    # ========== SAVE ENDPOINTS ==========
    print_header("SAVE SCORED IDEA")
    
    # Test 5: Save Scored Idea
    test_endpoint(
        "POST",
        "SaveScoredIdea",
        params={
            "Keyword": "test keyword from python",
            "Brand": "VitCornu",
            "scores_p": "4",
            "scores_a": "3",
            "scores_v": "4",
            "scores_e": "4",
            "search_summary": "Test search summary",
            "reasoning": "Test AI reasoning"
        },
        description="Save a new PAVE-scored idea"
    )
    
    # ========== BRIEF ENDPOINTS ==========
    print_header("BRIEF ENDPOINTS")
    
    # Test 6: Update Brief and Status (requires existing ID)
    test_endpoint(
        "PUT",
        "UpdateBriefAndStatus",
        data={
            "id": "1",
            "brief_text": "## Test Authority Brief\n\nThis is a test brief generated by Python script."
        },
        description="Update authority brief for item ID 1"
    )
    
    # ========== STATUS UPDATE ENDPOINTS ==========
    print_header("STATUS UPDATE ENDPOINTS")
    
    # Test 7: Update Content Status
    test_endpoint(
        "PUT",
        "UpdateContentStatus",
        data={
            "id": "1",
            "new_status": "In Production"
        },
        description="Update status to 'In Production' for item ID 1"
    )
    
    print_header("TEST SUITE COMPLETE")
    print("\n✨ All tests finished!\n")

if __name__ == "__main__":
    main()
